### ISSUE TITLE
fleans management error

### ISSUE THREAD

**Issue by nightBaker** [nightBaker/fleans#373]
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The value 'bpmnEditor.registerDirtyCallback' is not a function.
      Error: The value 'bpmnEditor.registerDirtyCallback' is not a function.
          at http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:510
          at h.resolveInvocationHandler (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:1428)
          at S (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:6453)
          at b.processJSCall (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:4444)
          at b.beginInvokeJSFromDotNet (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:4129)
          at Cn._invokeClientMethod (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:68829)
          at Cn._processIncomingData (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:66188)
          at Cn.connection.onreceive (http://l
ocalhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:59829)
          at i.onmessage (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:83922)
      Microsoft.JSInterop.JSException: The value 'bpmnEditor.registerDirtyCallback' is not a function.
      Error: The value 'bpmnEditor.registerDirtyCallback' is not a function.
          at http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:510
          at h.resolveInvocationHandler (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:1428)
          at S (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:6453)
          at b.processJSCall (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:4444)
          at b.beginInvokeJSFromDotNet (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:4129)
          at Cn._invokeClientMethod (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:68829)
          at Cn._processIncomingData (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:66188)
    
      at Cn.connection.onreceive (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:59829)
          at i.onmessage (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:83922)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, JSCallType callType, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Fleans.Web.Components.Pages.Editor.OnAfterRenderAsync(Boolean firstRender) in /Users/yerassylshalabayev/RiderProjects/fleans/src/Fleans/Fleans.Web/Components/Pages/Editor.razor:line 206
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'vYyYE9oCwiK7vuZ9qK9wEGHgQhBSDoMgkZHTVAD__h0'.
      Microsoft.JSInterop.JSException: The value 'bpmnEditor.registerDirtyCallback' is not a function.
      Error: The value 'bpmnEditor.registerDirtyCallback' is not a function.
          at http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:510
          at h.resolveInvocationHandler (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:1428)
          at S (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:6453)
          at b.processJSCall (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:4444)
          at b.beginInvokeJSFromDotNet (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:4129)
          at Cn._invokeClientMethod (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:68829)
          at Cn._processIncomingData (http://localhost:5104/_framework/blazor.web.
wmp8iwak4q.js:1:66188)
          at Cn.connection.onreceive (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:59829)
          at i.onmessage (http://localhost:5104/_framework/blazor.web.wmp8iwak4q.js:1:83922)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, JSCallType callType, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Fleans.Web.Components.Pages.Editor.OnAfterRenderAsync(Boolean firstRender) in /Users/yerassylshalabayev/RiderProjects/fleans/src/Fleans/Fleans.Web/Components/Pages/Editor.razor:line 206
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
i

**Comment by nightBaker** [comment]
**Root cause:** `bpmnEditor.js` and the other custom JS files in `wwwroot/js/` were loaded with plain URLs (no cache-busting). When PR #363 added `registerDirtyCallback` to `bpmnEditor.js`, browsers that had cached the old version kept serving it — causing the "not a function" JSException.

**Fix:** Added `@Assets["js/..."]` fingerprinting to all five custom JS files in `App.razor`, matching the pattern already used for `app.css` and `blazor.web.js`. The fingerprinted URL changes whenever the file content changes, forcing a fresh fetch.

Fix is on branch `claude/keen-keller-Ltk7L`.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by nightBaker** [comment]
This error was reported before the multi-tab editor feature landed. The `registerDirtyCallback` function was added in commit `4626888` (`feat(editor): multi-tab BPMN editor`, merged 2026-04-24 23:41) — about 5 hours after this issue was filed. The function is present in the current `bpmnEditor.js` (line 748).

The fix is already in `main`. This can be closed — the reporter should pull the latest code and clear their browser cache if the error persists.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by nightBaker** [comment]
Fixed in commit `0e23723` on branch `claude/keen-keller-ys2V7`.

Applied `@Assets[...]` fingerprinting to all five custom JS files in `App.razor`:
- `js/bpmnViewer.js`
- `js/fleansModdleExtension.js`
- `js/boundaryEventContextPad.js`
- `js/bpmnEditor.js`
- `js/dragResize.js`

This matches the pattern already used for `app.css` and `blazor.web.js`, ensuring browsers always fetch fresh versions when file content changes — preventing stale-cache errors like `registerDirtyCallback is not a function`.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by nightBaker** [comment]
## Design & Plan — #373 `bpmnEditor.registerDirtyCallback is not a function`

### 1. Problem

Opening `/editor` in the management UI throws a `JSException` from `Editor.razor:206` when `OnAfterRenderAsync` calls `bpmnEditor.registerDirtyCallback`. The function does exist in the current `bpmnEditor.js` (`src/Fleans/Fleans.Web/wwwroot/js/bpmnEditor.js:748`) — it was added by the multi-tab editor feature merged in commit `4626888` on 2026-04-24.

### 2. Root cause

`App.razor` references all five custom JS files in `wwwroot/js/` with **plain, un-fingerprinted URLs**:

```
src/Fleans/Fleans.Web/Components/App.razor:27..33
  <script src="js/bpmnViewer.js"></script>
  <script src="js/fleansModdleExtension.js"></script>
  <script src="js/boundaryEventContextPad.js"></script>
  <script src="js/bpmnEditor.js"></script>
  <script src="js/dragResize.js"></script>
```

Browsers therefore serve whatever `bpmnEditor.js` they last cached. Any session that had the editor open before the multi-tab change will keep getting the old script — which has no `registerDirtyCallback` — until the user manually does a hard reload.

The Blazor framework script and `app.css` already use `@Assets["..."]` fingerprinting (line 24); the local JS files were missed.

### 3. Fix

Switch all five `<script>` tags to use `@Assets["js/..."]`. The Razor asset map appends a content hash to the URL, so the URL changes every time the file changes — invalidating any stale browser cache without manual intervention.

```razor
<script src="@Assets["js/bpmnViewer.js"]"></script>
<script src="@Assets["js/fleansModdleExtension.js"]"></script>
<script src="@Assets["js/boundaryEventContextPad.js"]"></script>
<script src="@Assets["js/bpmnEditor.js"]"></script>
<script src="@Assets["js/dragResize.js"]"></script>
```

### 4. Status

**This fix is already in flight as PR #381** (`fix(#373, #282): JS cache-busting with @Assets + unify error code type int→string`, branch `claude/keen-keller-dNK4n`). The PR applies exactly the change above to `App.razor`.

PR #381 also bundles the unrelated #282 work (BPMN error code type `int → string`). That is a deliberate two-issue PR, not a scope creep — but it does mean #373 will not merge independently.

### 5. Plan

1. **No new code from this issue.** Track #373's resolution through PR #381.
2. Verify on the PR that the `App.razor` diff matches the snippet in §3 (it does, per the PR body's "Fix #373" section).
3. Manual verification, after #381 merges:
   - Pull `main`, run `dotnet run --project Fleans.Aspire`.
   - In a browser that previously hit the editor, open DevTools → Network and confirm `bpmnEditor.js` is requested with a fingerprint (`bpmnEditor.<hash>.js` or `?v=<hash>`).
   - Reload `/editor`; no `JSException` in the server logs, no console error.
   - Edit a tab, confirm the dirty marker appears (proves `registerDirtyCallback` is wired).
4. Close #373 once #381 is merged.

### 6. Done criteria

- PR #381 merged to `main`.
- `App.razor` references all five local JS files via `@Assets[…]`.
- Editor loads cleanly on a browser that had previously cached the pre-multi-tab `bpmnEditor.js` (no need for a hard reload).

### 7. Open questions

None — design is fully determined by the existing PR.

**Comment by nightBaker** [comment]
## Analysis Review — design & plan in latest comment

I verified the design's claims against the live PR and CI. The technical fix is correct, but the **plan as written is currently broken** — sending back to **In Analysis** for one important amendment plus a small guardrail.

---

### 🔴 Blocking
None. The 5-line `App.razor` change (`<script src="js/X">` → `<script src="@Assets["js/X"]">`) is the right fix. I confirmed the diff on PR #381 matches the snippet in §3 exactly:

```
src/Fleans/Fleans.Web/Components/App.razor  +5/-5
```

### 🟡 Important

1. **The "deliberate two-issue PR" justification is empirically wrong, and the plan is currently broken because of it.** PR #381 bundles #373 with #282 (`int → string` error-code unification), and the **`build / .NET` check on #381 is FAILING right now** — 29 compiler errors, all in test files, all from the #282 side of the bundle:

   ```
   error CS1503: Argument 2: cannot convert from 'int' to 'string'
       Fleans.Domain.Tests/WorkflowDomainEventsTests.cs(48,48)
   error CS1503: Argument 1: cannot convert from 'int' to 'string'
       Fleans.Domain.Tests/WorkflowExecutionTransitionTests.cs(989,27)
   error CS1503: Argument 2: cannot convert from 'string' to 'float'
       Fleans.Application.Tests/EventSubProcessErrorTests.cs(64,30)
   ... 26 more
   ```
   All errors stem from the error-code type change in #282 not being propagated to every test call site. **None** of these errors involve the #373 cache-bust change.

   Concretely: **the trivial cache-bust fix for #373 is being held hostage by an incomplete refactor in #282.** That contradicts the comment's claim that the bundle is "not scope creep." The plan's done criteria (§6 — "PR #381 merged to main") cannot be met until #282 is fixed, even though #373's contribution is ready.

   **Required amendment to the plan — pick one and write it down:**
   - **(A) Split:** open a new PR with *only* the `App.razor` diff against `main`, land it, close #373; let #381 continue carrying #282 alone. This is the lower-risk path because the cache-bust fix is content-hash invalidation — stale caches on prod browsers persist every day this waits.
   - **(B) Defend the bundle:** state explicitly *why* bundling is preferable despite the broken-CI evidence (e.g., "both touch `WorkflowInstance.Logging.cs:1` so a merge-order conflict is cheaper to avoid"), AND add an interim step to the plan: "fix the #282 test-call-site errors before considering this issue's work complete." Today the plan offloads that responsibility entirely.

2. **No regression guardrail for the asset-fingerprinting convention.** The root cause was a *convention violation* (5 of 6 local-script tags in `App.razor` were authored without `@Assets`). The plan fixes the symptoms but not the convention gap — a future contributor adding a 6th JS file is just as likely to write `<script src="js/foo.js">`. Two cheap options, please add one to the plan:
   - Append a one-liner to `CLAUDE.md` under **Code Conventions**: *"All `<script>` tags in `App.razor` (and any other Razor host) referencing local `wwwroot/` assets MUST use `@Assets["..."]` for cache-busting. CDN URLs are exempt."*
   - Or: a build-time check / Roslyn analyzer / regex CI step that fails when `App.razor` contains `src="js/`.

   Without this, this exact bug will recur.

### 🟢 Minor

1. **Branch hygiene:** earlier comments on this issue advertise three different feature branches as "the fix" — `claude/keen-keller-Ltk7L` (comment 0), `claude/keen-keller-ys2V7` (comment 2), and finally `claude/keen-keller-dNK4n` (comment 3 / PR #381). The first two should be deleted (or at minimum the comments should note they're abandoned) to avoid future confusion when grepping for the fix.

2. **Done criterion §6 bullet 3** ("Editor loads cleanly on a browser that had previously cached the pre-multi-tab `bpmnEditor.js`") is the right *behavioral* assertion but is not mechanically reproducible — a fresh CI runner has no stale cache. Either:
   - Drop it from §6 and keep it in the §5 manual checklist (where it already is), or
   - Add a concrete repro recipe (e.g. *"Open `/editor` once on `main@4626888~1` to seed the cache, then check out `main` and reload — must work without DevTools 'Disable cache.'"*) so a reviewer can verify against an objective procedure.

3. The plan correctly omits the two `unpkg.com` CDN `<script>` tags from the fix list, but doesn't say so. One sentence in §3 — *"The two `unpkg.com` bpmn-js scripts are out of scope; their URL already includes a version number."* — would close the loop and pre-empt review questions.

---

### Verdict

The technical content is right and trivial to verify, so I'm not blocking on correctness. But the plan currently asserts a done state (§6) that **PR #381 cannot reach in its current form** — the bundle's CI is red and the failing side has nothing to do with #373. Please pick one of A/B above, add the convention guardrail, then this is Ready.

→ Moving back to **In analysis**.

**Comment by nightBaker** [comment]
## Design & Plan v2 — #373 `bpmnEditor.registerDirtyCallback is not a function` (rework after analysis review)

Reworked in response to the [previous analysis review](#issuecomment-IC_kwDOKlA7oc8AAAABAar7GQ). All review points addressed below; final plan follows.

---

### 0. Changelog — what changed since v1

| Review point | Verdict in v1 | What v2 does |
| --- | --- | --- |
| 🟡 #1 — bundle is currently broken (PR #381 build/.NET = FAILURE due to #282 test sites) | Treated as fine ("deliberate two-issue PR, not scope creep") | **Adopt option (A): split.** Open a new branch off `main` carrying *only* the `App.razor` diff, open a PR that closes #373 alone, land it. PR #381 keeps #282 and remains the home of the error-code refactor. Justification matches the reviewer's: cache-bust is the lower-risk path because stale browser caches persist every day this waits, and #381's CI is currently red on a side of the bundle that has nothing to do with #373. |
| 🟡 #2 — no convention guardrail | Not addressed | Add a one-liner to **CLAUDE.md → Code Conventions** mandating `@Assets["..."]` for any local `wwwroot/` asset referenced from a Razor host. Adding a Roslyn analyzer / regex CI step is rejected as overkill for two host files. |
| 🟢 #1 — branch hygiene (`claude/keen-keller-Ltk7L`, `claude/keen-keller-ys2V7` advertised in earlier comments but abandoned) | Not addressed | Confirmed via `gh api repos/$REPO/branches`: both branches still exist on the remote, neither has an open PR. The implementing PR will delete them as part of cleanup (`git push origin --delete claude/keen-keller-Ltk7L claude/keen-keller-ys2V7`). |
| 🟢 #2 — done criterion §6 bullet 3 ("loads cleanly on a previously-cached browser") not mechanically reproducible on CI | Treated as a done criterion | Demoted to a §5 **manual verification** step with a concrete recipe (see §5). §6 done criteria are now CI-verifiable only. |
| 🟢 #3 — unpkg.com CDN scripts not called out as out of scope | Implicit | Now explicit in §3. |

---

### 1. Problem

Opening `/editor` in the management UI throws a `JSException` from `Editor.razor:206` when `OnAfterRenderAsync` calls `bpmnEditor.registerDirtyCallback`. The function does exist in the current `bpmnEditor.js` (`src/Fleans/Fleans.Web/wwwroot/js/bpmnEditor.js:748`) — it was added by the multi-tab editor feature merged in commit `4626888` on 2026-04-24 (PR #363). Browsers that had `/editor` open before that commit keep serving the pre-multi-tab `bpmnEditor.js` from cache, where the function does not exist.

### 2. Root cause

`App.razor` references all five custom JS files in `wwwroot/js/` with **plain, un-fingerprinted URLs**:

```
src/Fleans/Fleans.Web/Components/App.razor:25..32
  <script src="js/bpmnViewer.js"></script>
  ...
  <script src="js/fleansModdleExtension.js"></script>
  <script src="js/boundaryEventContextPad.js"></script>
  <script src="js/bpmnEditor.js"></script>
  <script src="js/dragResize.js"></script>
```

Browsers therefore serve whatever each JS file last cached. The Blazor framework script (`_framework/blazor.web.js`, line 23) and the two CSS files already use `@Assets["..."]` fingerprinting; the local JS files were missed when the host was first authored.

The two `unpkg.com` `<script>` / `<link>` tags (`bpmn-js@17.11.1`, lines 13–15 + 24 + 26) are **out of scope** — their URLs already include a pinned version, so the CDN handles cache invalidation for them.

### 3. Fix

Switch all five local `<script>` tags to use `@Assets["js/..."]`. The Razor asset map appends a content hash to the URL, so any source change yields a new URL — invalidating any stale browser cache without manual intervention.

```razor
<script src="@Assets["js/bpmnViewer.js"]"></script>
<script src="@Assets["js/fleansModdleExtension.js"]"></script>
<script src="@Assets["js/boundaryEventContextPad.js"]"></script>
<script src="@Assets["js/bpmnEditor.js"]"></script>
<script src="@Assets["js/dragResize.js"]"></script>
```

In addition, append the following bullet to **CLAUDE.md → Code Conventions** (after the existing Fluent UI Blazor bullet):

> - **Cache-busting for local Razor host assets**: every `<script>` or `<link>` in `App.razor` (or any other Razor host file) that references an asset under `wwwroot/` MUST go through `@Assets["..."]` so the URL carries a content hash. Externally-versioned CDN URLs (e.g. `https://unpkg.com/bpmn-js@17.11.1/...`) are exempt because the version segment in the URL already serves the same purpose. Without this, a published JS API addition can be invisible to browsers that cached the old file (root cause of #373).

### 4. Plan

1. **Split the work from PR #381.** Branch from latest `main`:
   ```
   git checkout main && git pull
   git checkout -b fix/373-asset-fingerprinting
   ```
2. Apply the diff in §3 to `src/Fleans/Fleans.Web/Components/App.razor` (5 line changes).
3. Append the convention bullet from §3 to `CLAUDE.md`.
4. `dotnet build` to confirm the asset map resolves (a typo in `@Assets["..."]` fails build).
5. Manual smoke per §5 below.
6. Push and open a PR titled `fix(#373): cache-bust local JS via @Assets in App.razor`. The PR body should `Closes #373` only — **not** #282.
7. After merge, delete abandoned branches: `git push origin --delete claude/keen-keller-Ltk7L claude/keen-keller-ys2V7`.
8. Do **not** touch PR #381. It continues to carry #282 and will land on its own timeline once the test-call-site errors there are fixed (tracked under #282).

### 5. Manual verification

After the PR merges and you have rebuilt locally:

- Run `dotnet run --project Fleans.Aspire`.
- In a browser **that previously hit `/editor` on a build older than commit `4626888`** (or simulate by checking out `4626888~1` first, opening `/editor`, then checking back out to the merged `main` and reloading without DevTools "Disable cache"), open `/editor`.
- Expected: page loads without a `JSException` in the server logs and without a console error mentioning `registerDirtyCallback`.
- DevTools → Network → confirm `bpmnEditor.js` is requested under a fingerprinted URL (e.g. `bpmnEditor.<hash>.js` or `?v=<hash>`).
- Edit a tab, confirm the dirty marker (`*`) appears in the tab title — proves `registerDirtyCallback` is wired and being invoked.

### 6. Done criteria (CI-verifiable)

- The split PR is merged to `main`.
- `App.razor` references all five local JS files via `@Assets[…]` and the build is green.
- The new convention bullet is present in `CLAUDE.md`.
- `claude/keen-keller-Ltk7L` and `claude/keen-keller-ys2V7` no longer exist on `origin`.

### 7. Open questions

None. The split is decided; the convention text is decided; manual verification is documented.

**Comment by nightBaker** [comment]
## Analysis Review v2 — design & plan in latest comment

I re-verified every v1 review point against the live repo and PR state. The v2 plan addresses all of them cleanly.

**State checks (just now):**
- PR #381 is `OPEN`, `MERGEABLE` but `mergeStateStatus=UNSTABLE`, `build=FAILURE` — exactly the broken-bundle premise the split decision rests on. ✅
- PR #381's changed files include `src/Fleans/Fleans.Web/Components/App.razor` (alongside 21 other files for the #282 refactor). The duplication is real. ✅
- `claude/keen-keller-Ltk7L` and `claude/keen-keller-ys2V7` still exist on `origin`. ✅
- `App.razor` on `main` still has `<script src="js/bpmnViewer.js">`-style plain URLs at lines 27–33. The fix has not landed yet. ✅

### 🔴 Blocking
None.

### 🟡 Important
None. The v1 review's two main asks (split the bundle, add a convention guardrail) are both honored, and the manual-verification recipe is now mechanically reproducible. The "reject the analyzer/CI step as overkill" judgment is defensible for a 2-host-file project — accepted.

### 🟢 Minor (not blocking; address inline if convenient)

1. **Coordination with PR #381 isn't documented.** §4 step 8 says "Do not touch PR #381" — that's right, but the new PR and #381 will both contain the same 5 `App.razor` lines. After the split lands on `main`:
   - Git's 3-way merge will resolve the `App.razor` rebase as a no-op (both sides apply identical changes), so this is mechanically painless.
   - But the maintainer of #381 should know to **drop the now-redundant `App.razor` lines from #381's diff on the next rebase** so the PR's body stays focused on #282 alone. One sentence in §4 step 8 covers this — e.g., *"After this PR merges, drop the `App.razor` lines from PR #381 in the next rebase; they're now in `main` from this PR."*

2. **The convention bullet text references issue #373 inline** (`"...root cause of #373"`). That ties a permanent CLAUDE.md guideline to a transient issue ID. Two existing CLAUDE.md sections reference issues (`#366`, `#288`, `#230/#231`) in the same form, so it's stylistically consistent — accept as written, but if you want to depart from that pattern, drop the parenthetical entirely (the convention stands on its own merit).

3. **Step 7 (delete abandoned branches) is unrelated cleanup riding along on this PR's lifecycle.** Same anti-bundling principle that motivated the split applies — branch deletion can be its own one-line task and shouldn't gate "done" on this issue. I'd accept either: keep step 7 but mark it explicitly *"best-effort cleanup, not blocking — runs after merge"*, or drop it from this issue entirely. Not worth a re-review either way.

### Verdict

The v2 plan is implementable as-written. All 🟢 items are stylistic — none change the diff or the order of operations.

→ Moving to **Ready**.

**Comment by nightBaker** [comment]
Implementation pushed in PR https://github.com/nightBaker/fleans/pull/383 (branch `fix/373-asset-fingerprinting`).

Closes #373 alone, per Plan v2 §4 — the `App.razor` 5-line diff is split from PR #381 so it can land while #381 continues to carry the unrelated #282 refactor on a build-FAILURE branch. Build is green locally; CI will validate.

Moved board to **In Review**.
